theme = "hugo-base16-theme"
baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Across the Tidyverse"
preserveTaxonomyNames = true
disqusShortname = "aammd"
googleAnalytics = ""
publishDir = "docs"
publishdir = "docs"
